### ISSUE TITLE
`forge()` does not write the modified message to `out`

### ISSUE THREAD

**Issue by pavel-kirienko** [resilar/crchack#10]
The docs state that `out` is populated with the modified message but it is not:

https://github.com/resilar/crchack/blob/7902c0541931b352c8df838e11acc9e558a0454d/forge.h#L31

The out argument is currently unused. I might be being overly pedantic since the docs are admitted to be incorrect, but still.

Thank you for this tool, by the way, it is quite helpful!

**Comment by resilar** [comment]
Thanks for pointing that out! 286a859 fixes the documentation and improves the `forge()` interface a bit.
