### ISSUE TITLE
Doesn't work with my specific case

### ISSUE THREAD

**Issue by cjosepha** [resilar/crchack#4]
I tried, without success, to use custom parameters to force CRC on a file that is verified with something that looks like the [crc32-alder](http://www.mrob.com/pub/comp/crc-all.html) algorithm.

Here is the crc calculation code (that use a table):
>uint32_t crc32_init(void)
>{
>	return 0xffffffff;
>}
>
>uint32_t crc32_byte(uint32_t accum, uint8_t delta)
>{
>	return table[(accum ^ delta) & 0xff] ^ (accum >> 8);
>}
>
> uint32_t get_crc(unsigned char *buffer, size_t buffer_size) {
> 	uint32_t crc = crc32_init();
> 	for (int i = 0; i < buffer_size; i++) {
> 		crc = crc32_byte(crc, buffer[i]);
> 	}
> 	return crc;
> }

Here is the [code](sourceware.org/svn/prelink/trunk/src/makecrc.c) that has been used to generate the table (we can read that the polynomial is 0xedb88320):

Here are the parameters I tried and the message generated:

> -w32 -pedb88320
> FAIL! try giving 32 mutable bits more (got 32)

> -w32 -pedb88320 -iffffffff
> FAIL! try giving 32 mutable bits more (got 32)

> -w32 -pedb88320 -iffffffff -xff -rR
> FAIL! try giving 5 mutable bits more (got 32)

> -w32 -pedb88320 -iffffffff -rR
> FAIL! try giving 4 mutable bits more (got 32)

> -w32 -pedb88320 -iffffffff -xff
> FAIL! try giving 28 mutable bits more (got 32)

> -w32 -pedb88320 -iffffffff -xff -r
> FAIL! try giving 28 mutable bits more (got 32)

> -w32 -pedb88320 -iffffffff -xff -R
> FAIL! try giving 5 mutable bits more (got 32)

> -w32 -pedb88320 -iffffffff -R
> FAIL! try giving 4 mutable bits more (got 32)

> -w32 -pedb88320 -iffffffff -r
> FAIL! try giving 32 mutable bits more (got 32)

What am I doing wrong ?

**Comment by resilar** [comment]
You are using reversed polynomial. Normal representation of edb88320 is 04c11db7 (you can use http://www.simplycalc.com/crc32-text.php to convert between the two representations).

```sh
[crchack]% echo "foobar" | ./crchack -w32 -p04c11db7 - 42424242 | xxd                         
00000000: 666f 6f62 6172 0aa7 79e1 c9              foobar..y..
[crchack]% echo "foobar" | ./crchack -w32 -p04c11db7 - 42424242 | ./crchack -w32 -p04c11db7 -         
42424242
```
